name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu  # Remplacez par votre nom d'utilisateur
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "."
          target: "/home/ubuntu"  # Remplacez par le chemin de déploiement sur EC2

      - name: Run deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo apt update
            sudo apt install python3-venv
            python3 -m venv venv 
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py runserver 0.0.0.0:8000
